// Generated by https://quicktype.io

export interface IDepartmentAPI {
    errcode:    number;
    errmsg:     string;
    department: IDepartment[];
}

export interface IDepartment {
    id:       number;
    name:     string;
    name_en?:  string;
    parentid: number;
    order:    number;
}
